version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/kotlin-playground
    steps:
    - checkout
    - run:
        name: HELLO
        command: echo Hello from branch $CIRCLE_BRANCH