version: 2
jobs:
  build:

    working_directory: ~/circleci-kotlin-playground

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
    - setup_remote_docker
    - checkout

    - run:
        name: Install Local File
        command: mvn install:install-file -Dfile=kotlin-plugin-1.3.0-release-208.jar -DgroupId=org.jetbrains.kotlin -DartifactId=kotlin-plugin -Dversion=1.3.0 -Dpackaging=jar

    - run:
        name: Package
        command: mvn package -DskipTests=true

    - run:
        name: Docker Build
        command: docker build -t hexlabs/kotlin-playground:latest .

    - run:
        name: Docker Tag
        command: docker tag hexlabs/kotlin-playground:latest hexlabs/kotlin-playground:0.1.$CIRCLE_BUILD_NUM