version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/kotlin-playground
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle.kts" }}
    - run:
        name: Gradle Clean
        command: ./gradlew clean
    - run:
        name: Gradle Build
        command: ./gradlew build -DBUILD_NUM=$CIRCLE_BUILD_NUM
    - run:
        name: Bintray Upload
        command: ./gradlew bintrayUpload -DBUILD_NUM=$CIRCLE_BUILD_NUM -DBINTRAY_KEY=$BINTRAY_KEY

    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle.kts" }}

    - run:
      name: Docker Build
      command: docker build -t hexlabs/kotlin-playground:latest .

      - run:
          name: Docker Tag
          command: docker tag hexlabs/kotlin-playground:latest hexlabs/kotlin-playground:0.1.$CIRCLE_BUILD_NUM

      - run:
          name: Docker Login
          command: docker login -u hexlabsbuilder -p $DOCKER_HUB_PASSWORD

      - run:
          name: Docker Push
          command: |
            docker push hexlabs/kotlin-playground:latest
            docker push hexlabs/kotlin-playground:0.1.$CIRCLE_BUILD_NUM