version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/kotlin-playground
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle.kts" }}
    - run:
        name: Gradle Build
        command: ./gradlew clean build -DBUILD_NUM=$CIRCLE_BUILD_NUM
#    - run:
#        name: Bintray Upload
#        command: ./gradlew bintrayUpload -DBUILD_NUM=$CIRCLE_BUILD_NUM -DBINTRAY_KEY=$BINTRAY_KEY
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle.kts" }}