version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/repo

    steps:
    - checkout

    - run: mkdir generator

    - run: cd generator && git clone https://github.com/hexlabsio/kloudformation-specification-generator.git

    - run: cd generator/kloudformation-specification-generator && mvn install

    - run: mkdir kloudformation

    - run: cd kloudformation && git clone https://github.com/hexlabsio/kloudformation.git

    - run: cd kloudformation/kloudformation mkdir -p src/main/resources && mvn install

    - run: mvn package

    - run: mkdir build && mv target/*.jar build

    - run: npm install -g serverless

    - run: cd build && serverless deploy -v

#    - run: npm install -g cfn-create-or-update
#
#    - run: cfn-create-or-update --stack-name kotlin-course-client --template-body file://deployment.yml --region eu-west-1 --wait
#
#    - run: aws s3 sync ./build s3://xx