version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/repo

    steps:
    - checkout

    - run: mkdir generator

    - run: cd generator && git clone https://github.com/hexlabsio/kloudformation-specification-generator.git

    - run: cd generator/kloudformation-specification-generator && mvn install

    - run: mkdir kloudformation

    - run: cd kloudformation && git clone https://github.com/hexlabsio/kloudformation.git

    - run: cd kloudformation/kloudformation mkdir -p src/main/resources && mvn install

    - run: mvn package

    - run: mkdir -p build/target && mv target/playground-1.0-SNAPSHOT.jar build/target/playground.jar

    - run: mv serverless.yml build

    - run: npm install -g serverless

    - run: cd build && serverless deploy -v

    - run: echo uploading libs

    - run: ls -ltr lib

    - run: aws s3 sync ./lib s3://kotlin-playground-server-libs