version: 2
jobs:
  build:

    working_directory: ~/circleci-kotlin-playground

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:

    - checkout

    - run:  mvn install:install-file -Dfile=kotlin-plugin-1.3.0-release-208.jar -DgroupId=org.jetbrains.kotlin -DartifactId=kotlin-plugin -Dversion=1.3.0 -Dpackaging=jar

    - run: mkdir generator

    - run: cd generator && git clone https://github.com/hexlabsio/kloudformation-specification-generator.git

    - run: cd generator/kloudformation-specification-generator && mvn install -DskipTests=true

    - run: mkdir kloudformation

    - run: cd kloudformation && git clone https://github.com/hexlabsio/kloudformation.git

    - run: cd kloudformation/kloudformation && mkdir -p src/main/resources && mvn install -DskipTests=true

    - run: mvn package -DskipTests=true

    - run: mkdir -p build/target && mv target/playground-1.0-SNAPSHOT.jar build/target/playground.jar

    - store_artifacts:
        path: target/playground.jar

    - run: mv serverless.yml build

    - run: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash

    - run: sudo apt-get install -y nodejs

    - run: sudo npm install -g serverless

    - run: cd build && serverless deploy -v

    - run: echo uploading libs

    - run: ls -ltr lib

    - run: aws s3 sync ./lib s3://kotlin-playground-server-libs