version: 2
jobs:
  build:

    working_directory: ~/circleci-kotlin-playground

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:

    - checkout

#    - restore_cache:
#        key: circleci-kotlin-playground-{{ checksum "pom.xml" }}
#
#    - run: mvn dependency:go-offline
#
#    - save_cache:
#        paths:
#        - ~/.m2
#        key: circleci-kotlin-playground-{{ checksum "pom.xml" }}

    - run: mkdir generator

    - run: cd generator && git clone https://github.com/hexlabsio/kloudformation-specification-generator.git

    - run: cd generator/kloudformation-specification-generator && mvn install -DskipTests=true

    - run: mkdir kloudformation

    - run: cd kloudformation && git clone https://github.com/hexlabsio/kloudformation.git

    - run: cd kloudformation/kloudformation && mkdir -p src/main/resources && mvn install -DskipTests=true

    - run: mvn package -DskipTests=true

    - run: mkdir -p build/target && mv target/playground-1.0-SNAPSHOT.jar build/target/playground.jar

    - store_artifacts:
        path: target/playground.jar

    - run: mv serverless.yml build

    - run: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash

    - run: sudo apt-get install -y nodejs

    - run: sudo npm install -g serverless

    - run: cd build && serverless deploy -v

    - run: echo uploading libs

    - run: ls -ltr lib

    - run: aws s3 sync ./lib s3://kotlin-playground-server-libs