version: 2
jobs:
  build:

    working_directory: ~/circleci-kotlin-playground

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
    - setup_remote_docker
    - checkout

    - run: ls -latr ~

    - run:
        name: Download and Install Node
        command: |
          curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
          sudo apt-get install -y nodejs

    - run:
        name: Install CFN Scripts
        command: sudo npm install -g cfn-create-or-update

    - run:
        name: Install Local File
        command: mvn install:install-file -Dfile=kotlin-plugin-1.3.0-release-208.jar -DgroupId=org.jetbrains.kotlin -DartifactId=kotlin-plugin -Dversion=1.3.0 -Dpackaging=jar

    - run:
        name: Package
        command: mvn package -DskipTests=true

    - store_artifacts:
        path: template.yml

    - run:
        name: Docker Build
        command: docker build -t hexlabs/kotlin-playground:latest .

    - run:
        name: Docker Tag
        command: docker tag hexlabs/kotlin-playground:latest hexlabs/kotlin-playground:0.1.$CIRCLE_BUILD_NUM

    - run:
        name: Docker Login
        command: docker login -u hexlabsbuilder -p $DOCKER_HUB_PASSWORD

    - run:
        name: Docker Push
        command: |
          docker push hexlabs/kotlin-playground:latest
          docker push hexlabs/kotlin-playground:0.1.$CIRCLE_BUILD_NUM

#    - run:
#        name: Deploy  Stack
#        command: sudo cfn-create-or-update --stack-name hexlabs-kotlin-playground --template-body file://template.yml --timeout-in-minutes 60 --region eu-west-1 --wait --capability CAPABILITY_IAM
